security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
    encoders:
        App\Entity\Biglietto:
            algorithm: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\Biglietto
                property: username
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login: 
            pattern: ^/login
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        owner:  
            pattern:   ^/
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }

