<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '4d76a890500b6e12eac9573f3a9267dd',
  'DATABASE_URL' => 'mysql://root:Ekkoplayer01@localhost:3306/scuola',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => 'bounceat',
);
